/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    HelloWorld: typeof import('./../components/HelloWorld.vue')['default']
    Home: typeof import('./../components/Home.vue')['default']
    Other: typeof import('./../components/Other.vue')['default']
    RouterDemo: typeof import('./../components/RouterDemo.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TheHeroes: typeof import('./../components/TheHeroes.vue')['default']
  }
}
